Adds PR template per contributing guidelines
openai-php/laravel pull request #124
Opened 2024-10-31 05:35 UTC by peterramsing

### What:

- [ ] Bug Fix
- [ ] New Feature
- [x] Docs

### Description:

The `CONTRIBUTING.md` file links to the PR template that isn't there. This adds the one used from PEST and I added a `docs` line as well.

2024-10-31 15:09 UTC, peterramsing commented
One thing about this PR template is that it shows tasks as "undone". There might be a better way to do that but before I reinvent what is there in Pest I'll let it be for now.
![Screenshot 2024-10-31 at 08 08 51](https://github.com/user-attachments/assets/2a62e14f-537f-441d-80c6-eba9b91208d8)

2025-04-05 16:53 UTC, iBotPeaches requested changes
thanks! - minor typo

2025-04-05 16:53 UTC, iBotPeaches commented on .github/PULL_REQUEST_TEMPLATE.md
> +-->
Where it says "Pest" it should probably say "OpenAI PHP team"

2025-04-08 00:35 UTC, iBotPeaches approved these changes
Forgot I could just fix easy typos in PRs :) - fixed and merging.

2025-04-08 00:36 UTC, merged

2025-04-08 00:36 UTC, iBotPeaches commented
thanks!